import{WEATHER_LOCATION,n,temp,dateLabel,timeLabel,getWeatherCondition,weatherIcon}from"./weather-utils.js";
const q=s=>document.querySelector(s),safe=v=>v??"—",metric=(name,value,detail="")=>`<article class="weather-metric"><span>${name}</span><strong>${value}</strong>${detail?`<small>${detail}</small>`:""}</article>`;
export function renderForecast(d){const c=d.current||{},h=d.hourly||{},daily=d.daily||{},cond=getWeatherCondition(c.weather_code,c.is_day!==0);q("[data-weather-updated]").textContent=`Оновлено о ${timeLabel(c.time||new Date())}`;q("[data-weather-current]").innerHTML=`<div><span class="weather-location">${WEATHER_LOCATION.city}, ${WEATHER_LOCATION.country}</span><div class="weather-now"><span class="weather-now__icon">${weatherIcon(cond.icon,cond.label)}</span><strong>${temp(c.temperature_2m)}</strong><div><h2 id="weather-now-title">${cond.label}</h2><p>Відчувається як ${temp(c.apparent_temperature)}</p><p>Сьогодні: ${temp(daily.temperature_2m_min?.[0])} / ${temp(daily.temperature_2m_max?.[0])}</p></div></div></div>`;
 const nowIndex=Math.max(0,h.time?.findIndex(x=>new Date(x)>=new Date())??0),vis=n(h.visibility?.[nowIndex]);q("[data-weather-metrics]").innerHTML=[metric("Опади",`${Math.round(n(h.precipitation_probability?.[nowIndex],0))}%`),metric("Вітер",`${Math.round(n(c.wind_speed_10m,0))} км/год`),metric("Пориви",`${Math.round(n(c.wind_gusts_10m,0))} км/год`),metric("Вологість",`${Math.round(n(c.relative_humidity_2m,0))}%`),metric("Тиск",`${Math.round(n(c.surface_pressure,0))} hPa`),metric("UV",safe(Math.round(n(h.uv_index?.[nowIndex],0)))),metric("Видимість",vis==null?"—":`${Math.round(vis/1000)} км`)].join("");
 q("[data-weather-hourly]").innerHTML=(h.time||[]).slice(nowIndex,nowIndex+24).map((t,i)=>{const x=nowIndex+i,w=getWeatherCondition(h.weather_code?.[x],new Date(t).getHours()>6&&new Date(t).getHours()<20);return`<article class="weather-hour ${i===0?"is-current":""}"><time>${timeLabel(t)}</time>${weatherIcon(w.icon,w.label)}<strong>${temp(h.temperature_2m?.[x])}</strong><span>Опади ${Math.round(n(h.precipitation_probability?.[x],0))}%</span><small>${Math.round(n(h.wind_speed_10m?.[x],0))} км/год</small></article>`}).join("");
 q("[data-weather-daily]").innerHTML=(daily.time||[]).map((t,i)=>{const w=getWeatherCondition(daily.weather_code?.[i],true);return`<article class="weather-day"><time>${dateLabel(t)}</time>${weatherIcon(w.icon,w.label)}<span>${w.label}</span><strong>${temp(daily.temperature_2m_min?.[i])} / <em>${temp(daily.temperature_2m_max?.[i])}</em></strong><small>Опади ${Math.round(n(daily.precipitation_probability_max?.[i],0))}% · ${Math.round(n(daily.wind_speed_10m_max?.[i],0))} км/год</small></article>`}).join("");
 renderChart(h.time?.slice(nowIndex,nowIndex+24)||[],h.temperature_2m?.slice(nowIndex,nowIndex+24)||[],h.apparent_temperature?.slice(nowIndex,nowIndex+24)||[],q("[data-weather-chart]"));const sunrise=daily.sunrise?.[0],sunset=daily.sunset?.[0],duration=n(daily.daylight_duration?.[0],0);q("[data-weather-sun]").innerHTML=`<dl class="weather-facts"><div><dt>Схід сонця</dt><dd>${timeLabel(sunrise)}</dd></div><div><dt>Захід сонця</dt><dd>${timeLabel(sunset)}</dd></div><div><dt>Тривалість дня</dt><dd>${Math.floor(duration/3600)} год ${Math.round(duration%3600/60)} хв</dd></div></dl>`}
function renderChart(labels,a,b,root){if(!a.length){root.textContent="Дані недоступні";return}const all=[...a,...b].filter(Number.isFinite),min=Math.floor(Math.min(...all)-2),max=Math.ceil(Math.max(...all)+2),w=720,h=260,p=34,pts=arr=>arr.map((v,i)=>`${p+i*(w-2*p)/(arr.length-1)},${h-p-(v-min)*(h-2*p)/(max-min||1)}`).join(" ");root.innerHTML=`<svg class="weather-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Графік температури від ${Math.round(a[0])} до ${Math.round(a.at(-1))} градусів"><path d="M${p} ${h-p}H${w-p}M${p} ${p}V${h-p}"/><polyline class="actual" points="${pts(a)}"/><polyline class="feels" points="${pts(b)}"/></svg><div class="weather-legend"><span>Температура</span><span>Відчувається як</span></div>`}
export function renderHistory(d,days=14){const x=d.daily||{},slice=(a)=>a?.slice(-days)||[],max=slice(x.temperature_2m_max),min=slice(x.temperature_2m_min),mean=slice(x.temperature_2m_mean),rain=slice(x.precipitation_sum),labels=slice(x.time);if(!max.length||!min.length){error("[data-weather-history]","Історичні дані тимчасово недоступні.");return}renderChart(labels,max,min,q("[data-weather-history]"));q("[data-weather-history]").insertAdjacentHTML("beforeend",`<dl class="weather-summary"><div><dt>Максимум</dt><dd>${temp(Math.max(...max))}</dd></div><div><dt>Мінімум</dt><dd>${temp(Math.min(...min))}</dd></div><div><dt>Середня</dt><dd>${temp(mean.reduce((a,b)=>a+b,0)/(mean.length||1))}</dd></div><div><dt>Днів з опадами</dt><dd>${rain.filter(v=>v>0).length}</dd></div></dl>`)}
export function renderWarnings(items){const root=q("[data-weather-warnings]"),matches=(Array.isArray(items)?items:[]).filter(x=>/łód|lodz/i.test(`${x.wojewodztwo||""} ${x.teryt||""} ${x.tresc||""}`));root.innerHTML=matches.length?matches.map(x=>`<article class="weather-warning"><strong>${safe(x.nazwa_zdarzenia)}</strong><span>Діє до ${safe(x.obowiazuje_do)}</span><p>${String(x.tresc||"").slice(0,260)}</p></article>`).join(""):`<p class="weather-ok">Немає активних попереджень IMGW</p>`;root.insertAdjacentHTML("beforeend",'<a class="weather-action" href="https://meteo.imgw.pl/" target="_blank" rel="noopener">Перевірити на сайті IMGW ↗</a>')}
export function renderAir(data){const root=q("[data-weather-air]"),p=data.pollutants||{},status=data.status||"Дані доступні";root.innerHTML=`<strong class="weather-air-status">${status}</strong><p>${data.recommendation||"Якість повітря перевірена за офіційними даними."}</p><div class="weather-pollutants">${["PM2.5","PM10","NO2","O3"].map(k=>metric(k,p[k]?.value==null?"—":`${p[k].value} µg/m³`)).join("")}</div><small>Джерело: GIOŚ · ${data.station||"найближча станція"}</small>`}
export const error=(sel,text)=>{q(sel).innerHTML=`<p class="weather-error">${text}</p>`};
