import{WEATHER_LOCATION,storage}from"./weather-utils.js";
const forecastTTL=15*60e3,historyTTL=60*60e3,warningsTTL=10*60e3,airTTL=10*60e3;
async function cached(key,ttl,request){const hit=storage.get(key,ttl);if(hit)return{data:hit,stale:false,cached:true};try{const data=await request();storage.set(key,data);return{data,stale:false}}catch(error){const raw=localStorage.getItem(key);if(raw){try{return{data:JSON.parse(raw).data,stale:true,error}}catch{}}throw error}}
const json=async url=>{const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`${r.status}`);return r.json()};
export function fetchForecast(){const u=new URL("https://api.open-meteo.com/v1/forecast");u.search=new URLSearchParams({latitude:WEATHER_LOCATION.latitude,longitude:WEATHER_LOCATION.longitude,timezone:WEATHER_LOCATION.timezone,forecast_days:"14",current:"temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,weather_code,cloud_cover,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,is_day",hourly:"temperature_2m,apparent_temperature,precipitation_probability,weather_code,surface_pressure,visibility,wind_speed_10m,wind_direction_10m,wind_gusts_10m,uv_index",daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,sunrise,sunset,daylight_duration,wind_speed_10m_max,wind_gusts_10m_max,uv_index_max"});return cached("prywoz-weather-forecast",forecastTTL,()=>json(u))}
export function fetchHistory(){const end=new Date();end.setDate(end.getDate()-1);const start=new Date(end);start.setDate(start.getDate()-29);const iso=d=>d.toISOString().slice(0,10),u=new URL("https://historical-forecast-api.open-meteo.com/v1/forecast");u.search=new URLSearchParams({latitude:WEATHER_LOCATION.latitude,longitude:WEATHER_LOCATION.longitude,timezone:WEATHER_LOCATION.timezone,start_date:iso(start),end_date:iso(end),daily:"temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,wind_speed_10m_max"});return cached("prywoz-weather-history",historyTTL,()=>json(u))}
export function fetchWarnings(){return cached("prywoz-weather-warnings",warningsTTL,()=>json("https://danepubliczne.imgw.pl/api/data/warningsmeteo"))}
export function fetchAir(){return cached("prywoz-weather-air-v2",airTTL,()=>json("./api/weather.php?source=air"))}
export const TTL={forecast:forecastTTL,history:historyTTL,warnings:warningsTTL,air:airTTL,stations:864e5};
